"""Switch to Fernet-based PII encryption

Revision ID: 8ee495e23505
Revises: b9e6192fa312
Create Date: 2025-06-23 15:36:28.156313

"""
from alembic import op
import sqlalchemy as sa
from app import PIIEncryptedType


# revision identifiers, used by Alembic.
revision = '8ee495e23505'
down_revision = 'b9e6192fa312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', PIIEncryptedType("ENCRYPTION_KEY"), nullable=False))
        batch_op.add_column(sa.Column('dob_sum', sa.String(length=8), nullable=False))
        batch_op.alter_column(
            'name',
            existing_type=sa.VARCHAR(length=100),
            type_=PIIEncryptedType("ENCRYPTION_KEY"),
            postgresql_using='name::bytea',
            nullable=False
        )
        batch_op.alter_column(
            'email',
            existing_type=sa.VARCHAR(length=120),
            type_=PIIEncryptedType("ENCRYPTION_KEY"),
            postgresql_using='email::bytea',
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'email',
            existing_type=PIIEncryptedType("ENCRYPTION_KEY"),
            type_=sa.VARCHAR(length=120),
            postgresql_using='email::text',
            nullable=True
        )
        batch_op.alter_column(
            'name',
            existing_type=PIIEncryptedType("ENCRYPTION_KEY"),
            type_=sa.VARCHAR(length=100),
            postgresql_using='name::text',
            nullable=True
        )
        batch_op.drop_column('dob_sum')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
