"""create passkey credential tables v2

Revision ID: ed9de5ef6f79
Revises: 55f079e43ae6
Create Date: 2025-12-31 01:02:21.198065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed9de5ef6f79'
down_revision = '55f079e43ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('credential_id',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('aaguid')
        batch_op.drop_column('sign_count')
        batch_op.drop_column('transports')
        batch_op.drop_column('public_key')

    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('credential_id',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('aaguid')
        batch_op.drop_column('sign_count')
        batch_op.drop_column('transports')
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transports', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aaguid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.alter_column('credential_id',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transports', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aaguid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.alter_column('credential_id',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    # ### end Alembic commands ###
