"""Initial clean migration

Revision ID: eee779989ddd
Revises: 
Create Date: 2025-04-13 05:13:00.156466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee779989ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('qr_id', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=256), nullable=False),
    sa.Column('block', sa.String(length=1), nullable=False),
    sa.Column('passes_left', sa.Integer(), nullable=True),
    sa.Column('last_tap_in', sa.DateTime(), nullable=True),
    sa.Column('last_tap_out', sa.DateTime(), nullable=True),
    sa.Column('is_rent_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_property_tax_enabled', sa.Boolean(), nullable=True),
    sa.Column('owns_seat', sa.Boolean(), nullable=True),
    sa.Column('insurance_plan', sa.String(), nullable=True),
    sa.Column('insurance_last_paid', sa.DateTime(), nullable=True),
    sa.Column('second_factor_type', sa.String(), nullable=True),
    sa.Column('second_factor_secret', sa.String(), nullable=True),
    sa.Column('second_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('has_completed_setup', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tap_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('tap_in_time', sa.DateTime(), nullable=True),
    sa.Column('tap_out_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date_funds_available', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('tap_sessions')
    op.drop_table('purchase')
    op.drop_table('students')
    # ### end Alembic commands ###
